apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: finance
spec:
  containers:
  - name: redis
    image: redis
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: size
         operator: In
         values:
         - Large
         - Medium
