apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: finance
spec:
  containers:
  - name: redis
    image: redis
  tolerations:
  - key: "app"
    operator: "Equall"
    value: "blue"
    effect: "NoSchedule"
